server:
  port: 8888
security:
  user:
    password: mypassword
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mambat/spring-cloud-config-data.git
          clone-on-start: true
